### ISSUE TITLE
Cannot `make` on Arduino 1.8.19 & Teensyduino 1.58

### ISSUE THREAD

**Issue by hobbsbros** [MASLAB/TAMProxy-Firmware#2]
TAMProxy does not compile correctly on Arduino 1.8.19 & Teensyduino 1.58.

Error message:
```
[CXX]	src/DeviceList.cpp
In file included from cores/teensy4/WProgram.h:69:0,
                 from src/DeviceList.cpp:2:
cores/teensy4/IntervalTimer.h: In member function 'uint32_t IntervalTimer::cyclesFromPeriod(period_t)':
cores/teensy4/IntervalTimer.h:123:17: error: 'is_arithmetic_v' is not a member of 'std'
   static_assert(std::is_arithmetic_v<period_t>, "Period must be arithmetic");
                 ^
cores/teensy4/IntervalTimer.h:123:46: error: expected primary-expression before '>' token
   static_assert(std::is_arithmetic_v<period_t>, "Period must be arithmetic");
                                              ^
cores/teensy4/IntervalTimer.h:123:47: error: expected primary-expression before ',' token
   static_assert(std::is_arithmetic_v<period_t>, "Period must be arithmetic");
                                               ^
cores/teensy4/IntervalTimer.h:127:6: error: expected '(' before 'constexpr'
   if constexpr (std::is_integral_v<period_t>)       // handles all integral types
      ^
cores/teensy4/IntervalTimer.h:129:6: error: expected '(' before 'constexpr'
   if constexpr (std::is_floating_point_v<period_t>) // handles all float types
      ^
make: *** [Makefile:155: /home/team-2/TAMProxy-Firmware/build/src/DeviceList.o] Error 1
```

**Comment by hobbsbros** [comment]
Requires update to Arduino 2.x.

**Comment by nmoroze** [comment]
This is interesting, I ran into this problem before but it went away with Arduino 1.8.19 and Teensyduino 1.58 once I got the magic values in the `OPTIONS` right: `-DARDUINO=10813 -DTEENSYDUINO=159`. 

This might be a Mac vs Ubuntu difference though, so it sounds good to go with Arduino 2.x if that works on the NUCs. It also seems nicer to use newer versions anyways. I'd suggest updating `README.md` accordingly, since that documents using Arduino 1.8.19.

**Comment by hobbsbros** [comment]
Very interesting!  Thank you for sharing the magic `OPTIONS`, I plan to test TAMProxy's compilation on my personal Ubuntu machine this afternoon, so I'll see if the magic `OPTIONS` have an effect.

No worries about the issue... I plan to update the Readme and close it today.

**Comment by nmoroze** [comment]
Great! Note those values for OPTIONS should already be set in the Makefile
in the teensy4 branch, so they probably are what you were using already.
